Redesign
Kibeshev/Themoviedb pull request #1
Opened 2019-07-15 11:01 UTC by Kibeshev

making a new design

2019-07-15 11:07 UTC, ismetanin requested changes

2019-07-15 11:07 UTC, ismetanin commented on Themoviedb/MoviesViewController.swift
> +    var urlStr = "https://api.themoviedb.org/3/movie/popular?api_key=4cb1eeab94f45affe2536f2c684a5c9e&page=1"
Мне кажется, что раз ты её устанавливаешь извне, то стоит эту строку оставить тут пустой
И давай не использовать скоращения в названиях, если то есть не `str`, а `string`

2019-07-15 11:07 UTC, ismetanin commented on Themoviedb/MoviesViewController.swift
> +    var segmentVC: SegmentViewController?
А зачем это тут?

2019-07-15 11:07 UTC, ismetanin commented on Themoviedb/PageViewController.swift
> +    lazy var viewControllerList = arrayVC()
А почему не `private`?

2019-07-15 11:07 UTC, ismetanin commented on Themoviedb/PageViewController.swift
> +    weak var segmentViewController: SegmentViewController?
А зачем тут это?

2019-07-15 11:07 UTC, ismetanin commented on Themoviedb/PageViewController.swift
> +    func setPage(index: Int) {
А почему не `private`?

2019-07-15 11:07 UTC, ismetanin commented on Themoviedb/SegmentViewController.swift
> +    func setIndex(index: Int) {
Кажется этот метод не используется

2019-07-15 11:07 UTC, ismetanin commented on Themoviedb/SegmentViewController.swift
> +    @IBOutlet private weak var sControl: UISegmentedControl!
Тут стоит поменять название и дать более осмысленное

2019-07-15 11:30 UTC, Kibeshev commented on Themoviedb/PageViewController.swift
> +    func setPage(index: Int) {
использую эту функцию в другом классе

2019-07-15 11:34 UTC, Kibeshev commented on Themoviedb/MoviesViewController.swift
> +    var segmentVC: SegmentViewController?
Согласен. Видимо забыл убрать, когда решил сменить реализацию задачи. Убрал

2019-07-15 11:48 UTC, Kibeshev commented on Themoviedb/PageViewController.swift
> +    weak var segmentViewController: SegmentViewController?
использую для связи между контролерами в файле SegmentViewController.swift / методе prepare. Не до конца понимаю как это работает(

2019-07-15 12:02 UTC, ismetanin commented on Themoviedb/PageViewController.swift
> +    weak var segmentViewController: SegmentViewController?
Ага, увидел, ну давай подумаем, и разберемся
Ответь на вопросики:
1) Зачем `SegmentViewController` знать о `PageViewController`?
2) Что такое метод `prepare` и зачем он? Когда он вызывается?

2019-07-15 12:06 UTC, ismetanin commented on Themoviedb/SegmentViewController.swift
> +class SegmentViewController: UIViewController {
Может назовем это как-то более предметно? Это же сегмент специально для списка фильмов, может что-то в духе "MoviesSegmentViewController"

2019-07-15 12:06 UTC, ismetanin commented on Themoviedb/PageViewController.swift
> +class PageViewController: UIPageViewController, UIPageViewControllerDelegate {
Как-то непонятно что это за пейдж контроллер, их же может быть много, предлагаю назвать "MoviesPageViewController"

2019-07-15 12:26 UTC, ismetanin commented on Themoviedb/PageViewController.swift
> +    weak var segmentViewController: SegmentViewController?
И ещё вопросик:
3. Как вообще используется `PageViewController` в `SegmentViewController`?

2019-07-15 12:26 UTC, ismetanin commented on Themoviedb/SegmentViewController.swift
> +    func segmentTapped(target: UISegmentedControl) {
А вот этот метод можно сделать приватным

2019-07-15 13:19 UTC, Kibeshev commented on Themoviedb/PageViewController.swift
> +    weak var segmentViewController: SegmentViewController?
1. PageViewController хранит в себе массив контроллеров, каждый из которых выполняет свою задачу(загрузку нужного списка фильмов), PageViewController лежит внутри SegmentViewController, чтоб я мог переключать разные контроллеры по нажатию на SegmentedController

2019-07-16 07:38 UTC, Kibeshev commented on Themoviedb/PageViewController.swift
> +    weak var segmentViewController: SegmentViewController?
2. Метод prepare передает данные из SegmentViewController в PageViewController и обрано. Это сделано для того, чтоб я мог по нажатию на segmentedControl выбирать нужную страницу по индексу из файла MoviesPageViewController/viewControllerList

2019-07-16 07:45 UTC, ismetanin requested changes

2019-07-16 07:45 UTC, ismetanin commented on Themoviedb/PageViewController.swift
> +//  PageViewController.swift
Название класса поменял, а название файла старое осталось

2019-07-16 07:45 UTC, ismetanin commented on Themoviedb/SegmentViewController.swift
> +//  SegmentViewController.swift
Тут тоже у файла старое название осталось

2019-07-16 07:45 UTC, ismetanin commented on Themoviedb/SegmentViewController.swift
> +            vc.segmentViewController = self
В `MoviesPageViewController` переменная `segmentViewController` не используется

2019-07-16 07:45 UTC, ismetanin commented on Themoviedb/RedTestViewController.swift
> +class RedTestViewController: UIViewController {
Может удалим это? Мне кажется не стоит сливать в мастер какой-то тестовый код

2019-07-16 08:06 UTC, Kibeshev commented on Themoviedb/RedTestViewController.swift
> +class RedTestViewController: UIViewController {
этот класс будет использоваться для поиска , для него уже есть заготовка в Tab Bar , переименовал его более предметно

2019-07-16 08:10 UTC, Kibeshev commented on Themoviedb/SegmentViewController.swift
> +//  SegmentViewController.swift
изменил

2019-07-16 08:10 UTC, Kibeshev commented on Themoviedb/PageViewController.swift
> +//  PageViewController.swift
исправил

2019-07-16 08:19 UTC, ismetanin approved these changes

2019-07-16 08:23 UTC, merged