Favorites screen
Kibeshev/Themoviedb pull request #10
Opened 2019-08-09 12:53 UTC by Kibeshev

#6 сделал логику сохранения и загрузки 
#7 сперва объект сохраняется в realm потом таблица загружается его из realm-а , удаляется тоже из Realm-a и таблицы сразу 
#8 все сделано как в дизайне и верста и удаление из списка , если таблица пустая , то появляется текст и говорит, что нужно добавить фильмы в избранное.

2019-08-09 13:13 UTC, ismetanin requested changes
Закоммитил всю папку подов, давай уберем и не будем добавлять в проект их

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/Realm Model/movieEntry.swift
> +//class RewriteGetPopularMoviesResponse: Object {
Мы же не оставляем за собой закомментированного кода

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/Realm Model/movieEntry.swift
> +class RewriteMovie: Object {
Как понимать название `RewriteMovie`? Давай как-то более осмысленно назовем, например `MovieDatabaseModel` и остальные модели в том же духе

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/Realm Model/movieEntry.swift
> +//    let videos: VideosResponse?
Тут тож комментированный код

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/Realm Model/movieEntry.swift
> +    override static func primaryKey() -> String? {
А напомни, зачем это?

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/Realm Model/movieEntry.swift
> +    @objc dynamic var vote_average = 0.0
Может будем использовать RealmOptional-ы?

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/MoviesCell.swift
> +import RealmSwift
Импорт есть, использования нет 🤷‍♂️

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +    static let completedLengthyDownload = Notification.Name("completedLengthyDownload")
Какая такая `LengthyDownload`?

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +    static let didCompleteTask = Notification.Name("didCompleteTask")
Какой такой `Task`?

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +    static let didReceiveData = Notification.Name("didReceiveData")
Какая `Data`? Непонятно, давай осмысленно назовем, не забудь ещё имя в правой части отредачить
+ давай ещё вынесем это в отдельный файлик `Notification.swift`, и положим в какую-нибудь папку типа  Extensions

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +        guard let myPuppy = realm?.objects(RewriteMovie.self) else {
Что за `myPuppy`?

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +                button.setImage(UIImage(named: "Image-4"), for: .normal)
Я не думаю, что Image-4 хорошее название для картинки

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +                print("стер из базы")
Давай не отправлять в мастер код с print-ами

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +    private func deleteFavorites() {
Может назовем `deleteFromFavorites`? А то это как-то не очень хорошо звучит, будто всё избранное удаляем

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +    func buttonTapped(sender: UIBarButtonItem) {
Какая buttonTapped?

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +    private var addFavorites = false
Может `isAddedToFavorites`?

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +    let favoritesVC = FavoritesMoviesViewController()
Зачем это тут? 😑

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/FavoritesMoviesViewController.swift
> +            let realm = try Realm()
Кажется тут отступа у кода не хватает, почему-то идет сразу под `do`, хотя `do` открывает новый скоуп `{}`

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/FavoritesMoviesViewController.swift
> +            let myPuppy = realm.objects(RewriteMovie.self)
Снова какой-то `puppy`

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/FavoritesMoviesViewController.swift
> +        if favoriteMovies.isEmpty {
Мне кажется тут не должно быть этой проверки, давай её делать в том месте, где таблицу перезагружаем

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/FavoritesMoviesViewController.swift
> +    private func loadMoviesFavorites() {
`loadFavoriteMovies` будет правильнее

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/FavoritesMoviesViewController.swift
> +    func onDidReceiveData(_ notification: Notification) {
`onDidReceiveData` какая data? Плохое название функции, непонятно что тут имеется ввиду, также непонятно когда эта функция вызовется

2019-08-09 13:13 UTC, ismetanin commented on Themoviedb/AppDelegate.swift
> +import RealmSwift
Импорт есть, использования нет

2019-08-09 13:13 UTC, ismetanin commented on Podfile — копия
> +platform :ios, '12.2'
Кажется это какой-то лишний файл

2019-08-09 13:36 UTC, Kibeshev commented on Themoviedb/FavoritesMoviesViewController.swift
> +        if favoriteMovies.isEmpty {
мне показалось хорошим решением сделать это тут, метод отвечает за количество ячеек , а если ячеек 0 то делает нужную команду

2019-08-09 13:40 UTC, Kibeshev commented on Themoviedb/Realm Model/movieEntry.swift
> +    override static func primaryKey() -> String? {
вообще эта функция нужна , чтобы один фильм несколько раз  в realm не записывался, но из-за обработки записи и удаления в realm в моем приложении это невозможно сделать

2019-08-09 13:45 UTC, ismetanin commented on Themoviedb/FavoritesMoviesViewController.swift
> +        if favoriteMovies.isEmpty {
Метод отвечает за количество ячеек, а не за изменение чего-то там у вью, так что это не совсем его работа

2019-08-09 13:46 UTC, ismetanin commented on Themoviedb/Realm Model/movieEntry.swift
> +    override static func primaryKey() -> String? {
Но в целом давай оставим, да

2019-08-09 13:46 UTC, Kibeshev commented on Themoviedb/FavoritesMoviesViewController.swift
> +        if favoriteMovies.isEmpty {
согласен, сейчас поправлю

2019-08-13 08:25 UTC, Kibeshev commented on Themoviedb/FavoritesMoviesViewController.swift
> +        if favoriteMovies.isEmpty {
получается на этом экране таблицу мы перезагружаем 2 раза , когда добавляем объект и когда стираем объект, поэтому данный код пришлось повторить 2 раза для загрузки и для удаления. Под правило трех ударов это не попадает, но прибавка строк в файле получилась большая, и еще не очень представляю как данный код обособить + строк получится все равно больше чем получалось в методе numberOfRowsInSection

2019-08-13 11:23 UTC, ismetanin commented on Themoviedb/FavoritesMoviesViewController.swift
> +        if favoriteMovies.isEmpty {
Немного не понял что ты имеешь ввиду. Как выглядит код, о котором ты говоришь?
Я подразумевал, что ты скрытие/отображение просто положишь в метод, который отвечает за заполнение массива с фильмами

2019-08-16 07:47 UTC, Kibeshev commented on Themoviedb/Realm Model/movieEntry.swift
> +    @objc dynamic var vote_average = 0.0
не получается использовать рилм опционалы , пишет что не может привести опциональный int к обычному , когда я сравниваю объекты по id

2019-08-16 08:05 UTC, ismetanin commented on Themoviedb/Realm Model/movieEntry.swift
> +    @objc dynamic var vote_average = 0.0
Мне кажется, что просто стоит проверку на нил сделать прежде чем сравнивать :)

2019-08-16 10:24 UTC, ismetanin requested changes

2019-08-16 10:24 UTC, ismetanin commented on Themoviedb/Extensions/Notifications.swift
> +    static let pressAddFavoritesButton = Notification.Name("pressAddFavoritesButton")
`Notification` же глобальная, а если кто-то захочет подписаться на нажатие какой-то другой кнопки избранного потом?
Давай какое-то более предметное имя дадим, что-то в духе `favoriteMoviesUpdated`

2019-08-16 10:24 UTC, ismetanin commented on Themoviedb/FavoritesMoviesViewController.swift
>              for i in myPuppy {
Опять какой-то myPuppy...
И давай не использовать названия короче трех символов, вместо `i` лучше что-то типа `databaseMovie` или хотя бы `element`

2019-08-16 10:24 UTC, ismetanin commented on Themoviedb/FavoritesMoviesViewController.swift
> +        isEmptyTableView()
Когда называют `isEmptySomething` это подразумевает, что метод/переменная должны возвращать `Bool`, чтобы писать выражения в духе `if isEmptyTableView` и они складывались в адекватные английские предложения `Если таблица пустая`
В данном случае лучше назвать как-то в духе `reloadAppearance` или можно в этот метод положить `tableView.reloadData()` и назвать весь его как `reloadData()`, и вызывать всегда не `tableView.reloadData()`, а просто `reloadData()`, так точно не забудем обновить emptyLabel

2019-08-16 10:24 UTC, ismetanin commented on Themoviedb/FavoritesMoviesViewController.swift
> +                for i in realmObjects {
Тут тоже `i` название - поправить стоит

2019-08-16 10:24 UTC, ismetanin commented on Themoviedb/FavoritesMoviesViewController.swift
>                  print("\(error)")
Можно же просто print(error)

2019-08-16 10:24 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +    private func deleteFromFavorites() {
Тут же не только удаление, тут и добавление в случае, если `isAddedToFavorites == false`

2019-08-16 10:24 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +            rewriteMovie.original_language = originalLanguageLabel?.text
А почему ты берешь из лейбла текст, а не из модели? Мы же вроде хотим сохранять то что с сервера приходит, а не что у нас в лейблах

2019-08-16 10:24 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +            rewriteMovie.original_title = movies?.original_title
А что за название такое, `rewriteMovie`?

2019-08-16 10:24 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +                if i.id.value == movies?.id {
Снова `i`, давай поправим

2019-08-16 10:24 UTC, ismetanin commented on Themoviedb/MovieDetailViewController.swift
> +        for i in realmObjects {
Давай поменяем `i` на нормальное имя

2019-08-20 12:12 UTC, ismetanin approved these changes

2019-08-20 12:12 UTC, merged