added Search Controller in Search Movies ViewController
Kibeshev/Themoviedb pull request #2
Opened 2019-07-16 11:06 UTC by Kibeshev

сделал tableView у SearcMoviesViewController для того чтобы реализовать searchController

2019-07-16 11:36 UTC, ismetanin requested changes

2019-07-16 11:36 UTC, ismetanin commented on Themoviedb/SearchMoviesViewController.swift
> +    var searchArray: [Movie] = []
А где марки и порядок методов?

2019-07-16 11:36 UTC, ismetanin commented on Themoviedb/SearchMoviesViewController.swift
> +    var moviesViewController: MoviesViewController?
А зачем это тут?

2019-07-16 11:36 UTC, ismetanin commented on Themoviedb/SearchMoviesViewController.swift
> +    var searchArray: [Movie] = []
И ещё кажется, что массив должен быть приватным

2019-07-16 11:36 UTC, ismetanin commented on Themoviedb/SearchMoviesViewController.swift
> +            withIdentifier: "TestCellSearch", for: indexPath
Давай какое-то более осмысленное название для идентификатора сделаем, например `SearchMoviesTableViewCell`

2019-07-16 12:01 UTC, Kibeshev commented on Themoviedb/SearchMoviesViewController.swift
> +    var moviesViewController: MoviesViewController?
для того чтобы делать поиск по этому контроллеру

2019-07-16 12:02 UTC, Kibeshev commented on Themoviedb/SearchMoviesViewController.swift
> +    var moviesViewController: MoviesViewController?
Я верно понял Гайд ?

2019-07-16 12:13 UTC, ismetanin commented on Themoviedb/SearchMoviesViewController.swift
> +    var moviesViewController: MoviesViewController?
Нет, не верно (Хотя возможно и верно, но мы не будем делать так)
У нас будет по-другому

Мы будем брать данные из API [по этому запросу](https://developers.themoviedb.org/3/search/search-movies) и отображать в таблице этого контроллера, причем нужно будет переиспользовать ячейки, которые используются в MovieListViewController

2019-07-16 12:16 UTC, Kibeshev commented on Themoviedb/SearchMoviesViewController.swift
> +    var moviesViewController: MoviesViewController?
окей , тогда в методе UISearchController(searchResultsController: нужно поставить nil )

2019-07-16 12:18 UTC, ismetanin commented on Themoviedb/SearchMoviesViewController.swift
> +    var moviesViewController: MoviesViewController?
Ага

2019-07-17 08:49 UTC, Kibeshev commented on Themoviedb/SearchMoviesViewController.swift
> +            withIdentifier: "TestCellSearch", for: indexPath
ячейку вообще эту уберу

2019-07-17 08:52 UTC, ismetanin approved these changes

2019-07-17 08:52 UTC, merged