Make search
Kibeshev/Themoviedb pull request #4
Opened 2019-07-17 13:11 UTC by Kibeshev

#3 
1. Сделал работающий поиск 

 ##
 Если найти фильм и нажать cancel, то строка поиска становится пустой, а список найденных фильмов остается загруженным. Не знаю баг это или фича, подскажи)

2019-07-17 13:19 UTC, ismetanin commented
> Если найти фильм и нажать cancel, то строка поиска становится пустой, а список найденных фильмов остается загруженным. Не знаю баг это или фича, подскажи)

Это баг, нужно очищать таблицу при очистке поиска - в таких моментах лучше смотреть как работает в системных приложениях

2019-07-17 13:23 UTC, Kibeshev commented
но смотри как получается, если мы ввели в активную строку поиска что-то и дальше нажал cancel чтоб поиск не был активным , так как я уже нашел нужный список и по нему ищу

2019-07-17 13:27 UTC, ismetanin requested changes

2019-07-17 13:27 UTC, ismetanin commented on Themoviedb/CellMoviesXIB.swift
> +//  CellMoviesXIB.swift
Мне кажется не стоит включать в название класса информацию о том, как верстается ячейка - давай вернем `CellMovies`, а ещё лучше давай назовем `MovieCell`, так на мой взгляд правильнее

2019-07-17 13:27 UTC, ismetanin commented on Themoviedb/CellMoviesXIB.swift
> +//  CellMoviesXIB.swift
xib соответственно тоже переименуем

2019-07-17 13:27 UTC, ismetanin commented on Themoviedb/ImagesCarouselViewController.swift
> +        navigationController?.tabBarController?.tabBar.isHidden = true
Таббар лучше скрывать через свойство .hidesBottomBarWhenPushed

https://stackoverflow.com/a/37804820/5654667 - тут ответ на Obj-C, но вроде всё просто

2019-07-17 13:27 UTC, ismetanin commented on Themoviedb/ImagesCarouselViewController.swift
> +        navigationController?.tabBarController?.tabBar.isHidden = true
В других местах тоже проверь, что убрал такую логику

2019-07-17 13:27 UTC, ismetanin commented on Themoviedb/MoviesViewController.swift
> +        tableView.layer.borderWidth = 0.3
А зачем бордер устанавливаешь таблице?

2019-07-17 13:27 UTC, ismetanin commented on Themoviedb/MoviesViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath) as? CellMoviesXIB
Давай давать идентификаторы соответствующие названию класса, то есть в этом случае `CellMoviesXIB`

2019-07-17 13:27 UTC, ismetanin commented on Themoviedb/SearchMoviesViewController.swift
> +        let searchAPI = """
Мне кажется стоит подумать над названием переменной, это, кажется, не API, а url

2019-07-17 13:27 UTC, ismetanin commented on Themoviedb/SearchMoviesViewController.swift
> +        manager.getMovie(urlString: searchAPI, completion: { [weak self] getPopularMoviesResponse in
Давай переименуем ещё заодним этот метод, он же получает список фильмов, а не один, так что лучше будет `getMovies`

2019-07-17 13:30 UTC, ismetanin commented
> но смотри как получается, если мы ввели в активную строку поиска что-то и дальше нажал cancel чтоб поиск не был активным , так как я уже нашел нужный список и по нему листаю

@Kibeshev смотри, нужно добавить сброс клавиатуры при скролле списка, можно сделать это при помощи `tableView.keyboardDismissMode = .onDrag`

2019-07-17 13:30 UTC, Kibeshev commented on Themoviedb/MoviesViewController.swift
> +        tableView.layer.borderWidth = 0.3
в дизайне есть граница между segmentedControll - ом и таблицей, на выходе получилось очень красиво

2019-07-18 12:36 UTC, ismetanin requested changes

2019-07-18 12:36 UTC, ismetanin commented on Themoviedb/SearchMoviesViewController.swift
>          searchViewController.searchResultsUpdater = self as? UISearchResultsUpdating
Вот эту строчку можно удалить, так как она не работает, твой контроллер не реализует `UISearchResultsUpdating` и тут получается nil

2019-07-18 12:36 UTC, ismetanin commented on Themoviedb/SearchMoviesViewController.swift
> +        controller.movies = self.searchMovies[indexPath.row]
Может и тут будем скрывать таббар?

2019-07-18 12:43 UTC, Kibeshev commented on Themoviedb/SearchMoviesViewController.swift
> +        controller.movies = self.searchMovies[indexPath.row]
согласен)

2019-07-18 12:44 UTC, ismetanin approved these changes

2019-07-18 12:45 UTC, merged